== Introducción a la programación estructurada

=== Paradigmas de programación

Los lenguajes de programación han evolucionado y se han creado nuevos
paradigmas que tienen como objetivo resolver nuevos tipos de problemas.

[arabic]
. Programación procedural
. Programación modular
. Abstracción de datos
. Programación orientada a objetos
. Programación genérica

==== Programación procedural

Este paradigma se basa en la creación de funciones o procedimientos como
nuevas operaciones.

Cuando los programas comienzan a ser más complejos, no es sencillo
resolver el problema como una única función. En el desarrollo del
software se estudian las tareas que queremos tener resueltas para el
problema, y se implementan los algoritmos correspondientes como
funciones o procedimientos.

Estas funciones ocultan los detalles del algoritmo que implementan, y
ofrecen la posibilidad de utilizarlo en base a una interfaz bien
definida.

Por ejemplo, podemos definir una función que contiene todos los pasos
necesarios para obtener la raíz cuadrada de un parámetro de doble
precisión en punto flotante.

....
double raizCuadrada(double x) {
    // Código para resolver la raíz cuadrada
}
....

=== Características de la programación estructurada

=== Codificación, depuración y compilación

=== Enlace, carga y ejecución de programas
